language: node_js
sudo: true
cache:
  yarn: true
  directories:
    - node
    - node_modules
dist: trusty
node_js:
  - '9.5'
branches:
  only:
  - master
script:
 - yarn lint
 - yarn jest
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  slack: pd-alumni:rAK13Qqe0ea2oBj8pWJgkHFA
